# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['aicoder_main.py'],
    pathex=['/home/zombie/ai-coder-kimi'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'aicoder.cli',
        'aicoder.client',
        'aicoder.config',
        'aicoder.session_state',
        'aicoder.docs_context',
        'aicoder.history',
        'aicoder.status',
        'aicoder.workspace',
        'aicoder.task',
        'aicoder.swarm_runner',
        'aicoder.agent',
        'aicoder.setup',
        'aicoder.repl_input',
        'aicoder.privileges',
        'aicoder.kimi',
        'aicoder.ui',
        'aicoder.gui',
        'aicoder.gui.app',
        'aicoder.gui.main_window',
        'aicoder.gui.chat_widget',
        'aicoder.gui.settings_widget',
        'aicoder.gui.theme',
        'aicoder.gui.autostart',
        'PyQt6',
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'PyQt6.QtCore',
        'PyQt6.QtNetwork',
        'certifi',
        'markdown',
        'markdown.extensions.fenced_code',
        'markdown.extensions.nl2br',
        'prompt_toolkit',
        'pyte',
        'pyte.screens',
        'pyte.streams',
        'pyte.modes',
        'getpass',
        'threading',
        'subprocess',
        'difflib',
        'pathlib',
        'json',
        'shutil',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['tkinter', 'PyQt5', 'wx', 'matplotlib'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='aicoder-kimi',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,
    console=True,
    onefile=True,
)
